import tempfile
import unittest
from pathlib import Path

from mi.workflows.hosts import HostBinding, sync_host_binding


class TestOpenClawAdapter(unittest.TestCase):
    def test_sync_generates_skills_and_registers_symlinks(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            workspace = Path(td) / "openclaw_ws"
            workspace.mkdir(parents=True, exist_ok=True)

            binding = HostBinding(
                host="openclaw",
                workspace_root=workspace,
                enabled=True,
                generated_rel_dir=".mi/generated/openclaw",
                register_symlink_dirs=[],
            )

            workflow = {
                "version": "v1",
                "id": "wf_test_1",
                "name": "Test Workflow",
                "enabled": True,
                "trigger": {"mode": "task_contains", "pattern": "deploy"},
                "mermaid": "flowchart TD\n  A-->B\n",
                "steps": [
                    {
                        "id": "s1",
                        "kind": "hands",
                        "title": "Do the thing",
                        "hands_input": "Implement the change and update docs.",
                        "check_input": "",
                        "risk_category": "other",
                        "policy": "values_judged",
                        "notes": "",
                    }
                ],
                "source": {"kind": "manual", "reason": "", "evidence_refs": []},
                "created_ts": "2026-01-01T00:00:00Z",
                "updated_ts": "2026-01-01T00:00:00Z",
            }

            res = sync_host_binding(binding=binding, project_id="p1", workflows=[workflow])
            self.assertTrue(res.get("ok"))

            # Generated artifacts.
            gen_root = binding.generated_root
            skill_dir = "mi-wf-test-1"
            skill_md = gen_root / "skills" / skill_dir / "SKILL.md"
            self.assertTrue(skill_md.is_file())
            txt = skill_md.read_text(encoding="utf-8")
            self.assertIn("metadata:", txt)
            self.assertIn("This skill is generated by Mind Incarnation (MI)", txt)
            self.assertIn("Implement the change and update docs.", txt)

            # Registration: symlink into workspace skills/.
            dst = workspace / "skills" / skill_dir
            self.assertTrue(dst.is_symlink())
            self.assertEqual(dst.resolve(), (gen_root / "skills" / skill_dir).resolve())

            # Re-sync with no workflows: should remove prior skill link (reversible).
            res2 = sync_host_binding(binding=binding, project_id="p1", workflows=[])
            self.assertTrue(res2.get("ok"))
            self.assertFalse(dst.exists())
