from __future__ import annotations

from typing import Any

from ._util import _to_json


def decide_next_prompt(
    *,
    task: str,
    hands_provider: str,
    runtime_cfg: dict[str, Any],
    project_overlay: dict[str, Any],
    thought_db_context: dict[str, Any] | None,
    active_workflow: dict[str, Any] | None = None,
    workflow_run: dict[str, Any] | None = None,
    recent_evidence: list[dict[str, Any]],
    hands_last_message: str,
    repo_observation: dict[str, Any],
    check_plan: dict[str, Any],
    auto_answer: dict[str, Any],
) -> str:
    return "\n".join(
        [
            "You are MI (Mind Incarnation), operating above Hands.",
            "Decide what to do next after a Hands batch, minimizing user burden.",
            "",
            "Constraints:",
            "- This prompt also serves as MI's 'closure' evaluation: if the task is complete, stop.",
            "- Only set status=done when confidence >= 0.6; otherwise keep working or run checks.",
            "- If status=done: set next_action=stop.",
            "- If status=blocked: set next_action=ask_user and provide ask_user_question.",
            "- Do NOT ask the user to 'confirm completion' as a default. MI self-evaluates done/blocked.",
            "- Ask the user ONLY when MI cannot proceed safely due to missing information or value conflicts.",
            "- If the project has no tests and verification is needed, ask the user ONCE per project for a testless verification strategy, then remember it (ProjectOverlay).",
            "- Prefer sending a next instruction to Hands over asking the user, when values/evidence allow.",
            "- Canonical values/preferences are provided via Thought DB context (especially values_claims); treat it as canonical when deciding.",
            "- If a minimal check plan is provided and should_run_checks=true, prefer sending hands_check_input to Hands before further work, unless user input is required first.",
            "- If needs_testless_strategy=true: first look for a canonical preference Claim in Thought DB context tagged 'mi:testless_verification_strategy'. If none exists, ask the user using testless_strategy_question.",
            "- If an auto-answer suggestion is provided and should_answer=true, prefer sending hands_answer_input to Hands (possibly combined with hands_check_input) instead of asking the user.",
            "- If auto_answer.needs_user_input=true, prefer asking the user using auto_answer.ask_user_question, unless you can safely answer from values/evidence already available (then send_to_hands).",
            "- If check_plan.should_run_checks=false but verification seems necessary, you may still propose a small set of checks via next_hands_input.",
            "",
            "Output:",
            "- Output MUST be a single JSON object matching the provided JSON Schema.",
            "- No markdown, no extra keys, no extra commentary.",
            "",
            "User task:",
            task.strip(),
            "",
            f"Hands provider: {hands_provider.strip() or '(unknown)'}",
            "",
            "Runtime config (structured):",
            _to_json(runtime_cfg),
            "",
            "ProjectOverlay:",
            _to_json(project_overlay),
            "",
            "Thought DB context (deterministic retrieval; may be empty):",
            _to_json(thought_db_context if isinstance(thought_db_context, dict) else {}),
            "",
            "Active workflow (if any; MI IR):",
            _to_json(active_workflow if isinstance(active_workflow, dict) else {}),
            "",
            "Workflow run state (best-effort cursor; if any):",
            _to_json(workflow_run if isinstance(workflow_run, dict) else {}),
            "",
            "Repo observation (read-only heuristic):",
            _to_json(repo_observation),
            "",
            "Minimal check plan (from plan_min_checks):",
            _to_json(check_plan),
            "",
            "Auto-answer suggestion (from auto_answer_to_hands):",
            _to_json(auto_answer),
            "",
            "Recent evidence (most recent last):",
            _to_json(recent_evidence),
            "",
            "Hands last message (raw):",
            hands_last_message.strip(),
            "",
            "Now decide the next action.",
        ]
    ).strip() + "\n"


def auto_answer_to_hands_prompt(
    *,
    task: str,
    hands_provider: str,
    runtime_cfg: dict[str, Any],
    project_overlay: dict[str, Any],
    thought_db_context: dict[str, Any] | None,
    repo_observation: dict[str, Any],
    check_plan: dict[str, Any],
    recent_evidence: list[dict[str, Any]],
    hands_last_message: str,
) -> str:
    return "\n".join(
        [
            "You are MI (Mind Incarnation), operating above Hands.",
            "Your job: answer Hands' question(s) as the user when possible, using values/preferences + evidence + memory, to minimize user burden.",
            "",
            "Constraints:",
            "- MI sits above Hands and only controls input + reads output.",
            "- MI does NOT intercept or gate Hands tool execution.",
            "- MI does NOT force Hands into step-by-step protocols.",
            "- Do NOT ask the user to confirm completion; only ask when blocked by missing info or value conflicts.",
            "- MI is authorized to answer on behalf of the user (including when the user task says 'ask the user') using values/preferences and evidence.",
            "- If Hands asks for permission to do external actions (network/install/push/publish), decide using values/preferences; if not clearly covered, set needs_user_input=true.",
            "- If values/preferences clearly imply the answer (e.g., default-deny for network/install unless necessary), answer Hands directly without asking the user, unless evidence shows it is necessary and allowed.",
            "- If Hands asks what it should do next (e.g., 'what would you like me to do'), answer by restating the user task and any relevant constraints; do NOT ask the user.",
            "- If the last Hands message does not contain a question or request for user input, set should_answer=false and hands_answer_input=\"\".",
            "",
            "Output rules:",
            "- Output MUST be a single JSON object matching the provided JSON Schema.",
            "- No markdown, no extra keys, no extra commentary.",
            "- Keep hands_answer_input concise and directly actionable; only include what Hands needs to proceed.",
            "",
            "User task:",
            task.strip(),
            "",
            f"Hands provider: {hands_provider.strip() or '(unknown)'}",
            "",
            "Runtime config (structured):",
            _to_json(runtime_cfg),
            "",
            "ProjectOverlay:",
            _to_json(project_overlay),
            "",
            "Thought DB context (canonical values/preferences; may be empty):",
            _to_json(thought_db_context if isinstance(thought_db_context, dict) else {}),
            "",
            "Repo observation (read-only heuristic):",
            _to_json(repo_observation),
            "",
            "Minimal check plan (from plan_min_checks):",
            _to_json(check_plan),
            "",
            "Recent evidence (most recent last):",
            _to_json(recent_evidence),
            "",
            "Hands last message (raw):",
            hands_last_message.strip(),
            "",
            "Now decide whether MI can answer Hands, and output the JSON.",
        ]
    ).strip() + "\n"

