from __future__ import annotations

from typing import Any

from ._util import _to_json


def loop_break_prompt(
    *,
    task: str,
    hands_provider: str,
    runtime_cfg: dict[str, Any],
    project_overlay: dict[str, Any],
    thought_db_context: dict[str, Any] | None,
    recent_evidence: list[dict[str, Any]],
    repo_observation: dict[str, Any],
    loop_pattern: str,
    loop_reason: str,
    hands_last_message: str,
    planned_next_input: str,
) -> str:
    return "\n".join(
        [
            "You are MI (Mind Incarnation), operating above Hands.",
            "MI detected a repeated stuck loop while trying to send the next instruction to Hands.",
            "",
            "Goal:",
            "- Break the loop with minimal user burden and minimal disruption to Hands autonomy.",
            "- Prefer a small rewrite of the next instruction to make progress or reduce uncertainty.",
            "",
            "Constraints:",
            "- MI only controls prompt input and reads output; MI does NOT intercept tools/commands.",
            "- Do NOT enforce rigid step-by-step protocols on Hands.",
            "- Do NOT ask the user by default. Only choose action=ask_user when truly blocked on missing info or value conflict.",
            "- If you choose action=run_checks_then_continue: provide a short check_intent; MI will plan checks separately.",
            "- If you choose action=rewrite_next_input: provide rewritten_next_input that is meaningfully different and likely to make progress.",
            "- You may choose stop_done only when evidence strongly implies task completion.",
            "- You may choose stop_blocked when MI cannot proceed safely without user input or external changes.",
            "",
            "Output rules:",
            "- Output MUST be a single JSON object matching the provided JSON Schema.",
            "- No markdown, no extra keys, no extra commentary.",
            "- Always include: action, confidence, rewritten_next_input, check_intent, ask_user_question, notes.",
            "",
            "User task:",
            task.strip(),
            "",
            f"Hands provider: {hands_provider.strip() or '(unknown)'}",
            "",
            "Runtime config (structured):",
            _to_json(runtime_cfg),
            "",
            "ProjectOverlay:",
            _to_json(project_overlay),
            "",
            "Thought DB context (canonical values/preferences; may be empty):",
            _to_json(thought_db_context if isinstance(thought_db_context, dict) else {}),
            "",
            "Repo observation (read-only heuristic):",
            _to_json(repo_observation),
            "",
            "Recent evidence (most recent last):",
            _to_json(recent_evidence),
            "",
            f"Loop pattern: {str(loop_pattern or '').strip()}",
            f"Loop reason: {str(loop_reason or '').strip()}",
            "",
            "Hands last message (raw):",
            (hands_last_message or "").strip(),
            "",
            "Planned next input to Hands (verbatim):",
            (planned_next_input or "").strip(),
            "",
            "Now output the loop break JSON.",
        ]
    ).strip() + "\n"

