from __future__ import annotations

from typing import Any

from ._util import _to_json


def workflow_progress_prompt(
    *,
    task: str,
    hands_provider: str,
    runtime_cfg: dict[str, Any],
    project_overlay: dict[str, Any],
    thought_db_context: dict[str, Any] | None,
    workflow: dict[str, Any],
    workflow_run: dict[str, Any],
    latest_evidence: dict[str, Any],
    last_batch_input: str,
    hands_last_message: str,
) -> str:
    return "\n".join(
        [
            "You are MI (Mind Incarnation).",
            "Infer workflow step progress from evidence, without enforcing step-by-step reporting.",
            "",
            "Goal:",
            "- Update MI's internal workflow cursor (best-effort): which steps are completed, and what the next step is.",
            "",
            "Constraints:",
            "- Do NOT ask the user questions.",
            "- Do NOT require Hands to follow a rigid protocol; Hands may complete multiple steps in one batch.",
            "- Only mark a step complete when evidence strongly implies it was completed.",
            "- You may mark multiple steps complete at once if Hands likely crossed them.",
            "- If you are uncertain, set should_update=false and keep next_step_id empty.",
            "",
            "Output rules:",
            "- Output MUST be a single JSON object matching the provided JSON Schema.",
            "- No markdown, no extra keys, no extra commentary.",
            "- completed_step_ids MUST be step ids from the provided workflow.steps list.",
            "- next_step_id MUST be a step id from the workflow.steps list, or empty when unknown/none.",
            "",
            "User task:",
            task.strip(),
            "",
            f"Hands provider: {hands_provider.strip() or '(unknown)'}",
            "",
            "Runtime config (structured):",
            _to_json(runtime_cfg),
            "",
            "ProjectOverlay (may include prior workflow_run state):",
            _to_json(project_overlay),
            "",
            "Thought DB context (canonical values/preferences; may be empty):",
            _to_json(thought_db_context if isinstance(thought_db_context, dict) else {}),
            "",
            "Active workflow (MI IR):",
            _to_json(workflow),
            "",
            "Current workflow_run state (prior):",
            _to_json(workflow_run),
            "",
            "Latest evidence (from extract_evidence):",
            _to_json(latest_evidence),
            "",
            "Last batch input MI sent to Hands (verbatim):",
            (last_batch_input or "").strip(),
            "",
            "Hands last message (raw):",
            (hands_last_message or "").strip(),
            "",
            "Now output the workflow progress JSON.",
        ]
    ).strip() + "\n"


def suggest_workflow_prompt(
    *,
    task: str,
    hands_provider: str,
    runtime_cfg: dict[str, Any],
    project_overlay: dict[str, Any],
    thought_db_context: dict[str, Any] | None,
    recent_evidence: list[dict[str, Any]],
    notes: str,
) -> str:
    return "\n".join(
        [
            "You are MI (Mind Incarnation).",
            "Suggest a reusable workflow IR only when it would significantly reduce user burden in future runs.",
            "",
            "Constraints:",
            "- MI sits above Hands and only controls input + reads output.",
            "- Do NOT enforce step-by-step protocol tyranny. Workflow steps should be coarse-grained and goal-oriented.",
            "- Only suggest a workflow when it is likely to repeat (or the benefit is extremely high).",
            "- Prefer project-scoped workflow suggestions by default (V1 solidification writes to the project store).",
            "- The workflow IR will be stored as MI source-of-truth; host workspace files are derived artifacts.",
            "- If you are not confident, set should_suggest=false and suggestion=null.",
            "",
            "Output rules:",
            "- Output MUST be a single JSON object matching the provided JSON Schema.",
            "- No markdown, no extra keys, no extra commentary.",
            "",
            "User task:",
            task.strip(),
            "",
            f"Hands provider: {hands_provider.strip() or '(unknown)'}",
            "",
            "Runtime config (structured):",
            _to_json(runtime_cfg),
            "",
            "ProjectOverlay:",
            _to_json(project_overlay),
            "",
            "Thought DB context (canonical values/preferences; may be empty):",
            _to_json(thought_db_context if isinstance(thought_db_context, dict) else {}),
            "",
            "Recent evidence (most recent last):",
            _to_json(recent_evidence),
            "",
            "Run notes:",
            (notes or "").strip(),
            "",
            "If you suggest a workflow:",
            "- Provide a stable signature string (used to count occurrences across runs).",
            "- Provide benefit=high ONLY when the user-burden reduction is substantial.",
            "- Provide a small number of steps (3-7). Each step MUST have an id.",
            "- Set workflow.enabled=false in the suggestion; MI decides whether to auto-enable.",
            "- Set workflow.id to an empty string.",
            "",
            "Now output the JSON.",
        ]
    ).strip() + "\n"


def edit_workflow_prompt(
    *,
    runtime_cfg: dict[str, Any],
    project_overlay: dict[str, Any],
    thought_db_context: dict[str, Any] | None,
    workflow: dict[str, Any],
    user_request: str,
) -> str:
    return "\n".join(
        [
            "You are MI (Mind Incarnation).",
            "Edit a stored workflow IR based on the user's natural-language request.",
            "",
            "Constraints:",
            "- Preserve workflow.id, workflow.version, and workflow.created_ts.",
            "- Make the smallest change that satisfies the request.",
            "- Keep step ids stable when possible; only add/remove steps when necessary.",
            "- Ensure every step has all required fields, even if empty strings.",
            "",
            "Output rules:",
            "- Output MUST be a single JSON object matching the provided JSON Schema.",
            "- No markdown, no extra keys, no extra commentary.",
            "",
            "Runtime config (structured):",
            _to_json(runtime_cfg),
            "",
            "ProjectOverlay:",
            _to_json(project_overlay),
            "",
            "Thought DB context (canonical values/preferences; may be empty):",
            _to_json(thought_db_context if isinstance(thought_db_context, dict) else {}),
            "",
            "Current workflow JSON:",
            _to_json(workflow),
            "",
            "User request:",
            (user_request or "").strip(),
            "",
            "Now output the edited workflow JSON + change_summary + conflicts + notes.",
        ]
    ).strip() + "\n"

